version: '3.4'

services:
  catalogdb:
    image: mongo

  mongoclient:
    image: mongoclient/mongoclient

  basketredis:
    image: redis

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portaineragent:
    image: portainer/agent:latest

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
  
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pdadmin_data: